name: "Hikvision-Baresip"
description: "Hikvision Baresip client for injecting RTSP video feed into an Asterisk conference"
version: "1.0"
slug: "hikvision_baresip"
url: "https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-baresip"
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:ro
